import { vi } from "vitest";
export const mockCreateIpc = () => ({
  openFileDialog: vi.fn(async () => "/path/to/meeting.mp3"),
  setMeetingSource: vi.fn(),
  transcribeMeeting: vi.fn(),
  diarizeMeeting: vi.fn(),
  createMeeting: vi.fn(),
  deleteMeeting: vi.fn(),
  clearMeeting: vi.fn(),
  listMeetings: vi.fn(),
  openMeeting: vi.fn(),
  renameMeeting: vi.fn(),
  updateSegment: vi.fn(),
  updateMfu: vi.fn(),
  generateMfu: vi.fn(),
  saveTextDialog: vi.fn(async () => null),
  listTaskModels: vi.fn(),
  downloadModel: vi.fn(),
  deleteModel: vi.fn(),
  onModelDownloadProgress: vi.fn(async () => () => {}),
  onTranscriptionPhase: vi.fn(async () => () => {}),
  onTranscriptionProgress: vi.fn(async () => () => {}),
  getSettings: vi.fn(async () => ({
    theme: "system",
    ui_language: "en",
    active_model_diarization: "none",
    export_file_type: "plain_text",
  })),
  setSetting: vi.fn(),
  collapseToBubble: vi.fn(),
  restoreMainFromBubble: vi.fn(),
  setBubbleAlwaysOnTop: vi.fn(),
  getRecorderShortcutStatus: vi.fn(async () => ({
    configured: "Control+Option+Space",
    active: true,
  })),
  setRecorderShortcut: vi.fn(),
  getCloudProviderConfig: vi.fn(async () => ({
    selected_provider: "deepgram",
    providers: [
      { id: "deepgram", name: "Deepgram", model: "Nova-3", configured: false },
      {
        id: "assemblyai",
        name: "AssemblyAI",
        model: "Universal-3.5 Pro",
        configured: false,
      },
      {
        id: "openai",
        name: "OpenAI",
        model: "GPT Transcribe",
        configured: false,
      },
    ],
  })),
  verifyCloudProviderApiKey: vi.fn(),
  listStreamingSessions: vi.fn(async () => []),
  openStreamingSession: vi.fn(),
  renameStreamingSession: vi.fn(),
  deleteStreamingSession: vi.fn(),
  clearStreamingSession: vi.fn(),
  createStreamingSession: vi.fn(),
  startStreamingSession: vi.fn(),
  stopStreamingSession: vi.fn(),
  getLiveCaptureSnapshot: vi.fn(async () => ({
    phase: "idle" as const,
    session_id: null,
    source: null,
    generation: 0,
    revision: 0,
    error: null,
  })),
  onLiveCaptureState: vi.fn(async () => () => {}),
  onOpenRecorderWorkspace: vi.fn(async () => () => {}),
  onStreamingWindow: vi.fn(async () => () => {}),
  onStreamingSources: vi.fn(async () => () => {}),
  onStreamingSessionEnded: vi.fn(async () => () => {}),
  onStreamingPartial: vi.fn(async () => () => {}),
  onStreamingError: vi.fn(async () => () => {}),
  generateStreamingMfu: vi.fn(),
  generateStreamingPrettify: vi.fn(),
  acceptStreamingPrettify: vi.fn(),
  revertStreamingPrettify: vi.fn(),
  generateRecorderPolish: vi.fn(),
  createRecorderDraft: vi.fn(),
  listRecorderSessions: vi.fn(async () => []),
  openRecorderSession: vi.fn(),
  renameRecorderSession: vi.fn(),
  deleteRecorderSession: vi.fn(),
  exportRecorderWav: vi.fn(),
  startRecorderSession: vi.fn(),
  stopRecorderSession: vi.fn(),
  recoverRecorderSession: vi.fn(),
  updateRecorderSegment: vi.fn(),
  getMicrophonePermissionStatus: vi.fn(async () => "authorized" as const),
  requestMicrophonePermission: vi.fn(async () => "authorized" as const),
  onRecorderSessionChanged: vi.fn(async () => () => {}),
  onRecorderSegmentCommitted: vi.fn(async () => () => {}),
  onRecorderPartial: vi.fn(async () => () => {}),
  onRecorderError: vi.fn(async () => () => {}),
  acceptRecorderPolish: vi.fn(),
  revertRecorderPolish: vi.fn(),
  translateStreamingWindow: vi.fn(),
  previewStreamingTranslation: vi.fn(),
  listStreamingTranslations: vi.fn(async () => []),
  setStreamingTranslationEnabled: vi.fn(),
  setStreamingTranslationTargetLanguage: vi.fn(),
  clearRecorderRecording: vi.fn(),
});
