import { vi } from "vitest";
export const mockCreateIpc = () => ({
  openFileDialog: vi.fn(async () => "/path/to/meeting.mp3"),
  setMeetingSource: vi.fn(),
  transcribeMeeting: vi.fn(),
  diarizeMeeting: vi.fn(),
  createMeeting: vi.fn(),
  deleteMeeting: vi.fn(),
  listMeetings: vi.fn(),
  openMeeting: vi.fn(),
  renameMeeting: vi.fn(),
  updateSegment: vi.fn(),
  updateNotes: vi.fn(),
  generateNotes: vi.fn(),
  saveTextDialog: vi.fn(async () => null),
  listTaskModels: vi.fn(),
  downloadModel: vi.fn(),
  deleteModel: vi.fn(),
  onModelDownloadProgress: vi.fn(async () => () => {}),
  onTranscriptionPhase: vi.fn(async () => () => {}),
  getSettings: vi.fn(async () => ({
    theme: "system",
    ui_language: "en",
    active_model_diarization: "none",
    export_file_type: "plain_text",
  })),
  setSetting: vi.fn(),
  listStreamingSessions: vi.fn(async () => []),
  openStreamingSession: vi.fn(),
  renameStreamingSession: vi.fn(),
  deleteStreamingSession: vi.fn(),
  startStreamingSession: vi.fn(),
  stopStreamingSession: vi.fn(),
  onStreamingWindow: vi.fn(async () => () => {}),
  onStreamingSources: vi.fn(async () => () => {}),
  onStreamingSessionEnded: vi.fn(async () => () => {}),
});
