import { vi } from "vitest";
export const mockCreateIpc = () => ({
  openFileDialog: vi.fn(async () => "/path/to/meeting.mp3"),
  setMeetingSource: vi.fn(),
  transcribeMeeting: vi.fn(),
  diarizeMeeting: vi.fn(),
  createMeeting: vi.fn(),
  deleteMeeting: vi.fn(),
  listMeetings: vi.fn(),
  openMeeting: vi.fn(),
  renameMeeting: vi.fn(),
  updateSegment: vi.fn(),
  updateMfu: vi.fn(),
  generateMfu: vi.fn(),
  saveTextDialog: vi.fn(async () => null),
  listTaskModels: vi.fn(),
  downloadModel: vi.fn(),
  deleteModel: vi.fn(),
  onModelDownloadProgress: vi.fn(async () => () => {}),
  onTranscriptionPhase: vi.fn(async () => () => {}),
  onTranscriptionProgress: vi.fn(async () => () => {}),
  getSettings: vi.fn(async () => ({
    theme: "system",
    ui_language: "en",
    active_model_diarization: "none",
    export_file_type: "plain_text",
  })),
  setSetting: vi.fn(),
  getCloudProviderConfig: vi.fn(async () => ({
    selected_provider: "deepgram",
    providers: [
      { id: "deepgram", name: "Deepgram", model: "Nova-3", configured: false },
      {
        id: "assemblyai",
        name: "AssemblyAI",
        model: "Universal-3.5 Pro",
        configured: false,
      },
      {
        id: "openai",
        name: "OpenAI",
        model: "GPT Live Transcribe",
        configured: false,
      },
    ],
  })),
  verifyCloudProviderApiKey: vi.fn(),
  listStreamingSessions: vi.fn(async () => []),
  openStreamingSession: vi.fn(),
  renameStreamingSession: vi.fn(),
  deleteStreamingSession: vi.fn(),
  createStreamingSession: vi.fn(),
  startStreamingSession: vi.fn(),
  stopStreamingSession: vi.fn(),
  onStreamingWindow: vi.fn(async () => () => {}),
  onStreamingSources: vi.fn(async () => () => {}),
  onStreamingSessionEnded: vi.fn(async () => () => {}),
  onStreamingPartial: vi.fn(async () => () => {}),
  onStreamingError: vi.fn(async () => () => {}),
  generateStreamingMfu: vi.fn(),
  generateStreamingPrettify: vi.fn(),
  acceptStreamingPrettify: vi.fn(),
  revertStreamingPrettify: vi.fn(),
  translateStreamingWindow: vi.fn(),
  listStreamingTranslations: vi.fn(async () => []),
});
